export const FETCH_CATS = 'FETCH_CATS';
export const GET_CATS = 'GET_CATS';
export const ERROR_CATS = 'ERROR_CATS';
export const SET_POST_CAT = 'SET_POST_CAT';
export const SET_VIEW_CAT = 'SET_VIEW_CAT';

export const SET_POST_CURRENT = 'SET_POST_CURRENT';
export const CREATE_POST = 'CREATE_POST';
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const ERROR_EDIT_POST = 'ERROR_EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const ERROR_DELETE_POST = 'ERROR_DELETE_POST';
export const VOTE_POST = 'VOTE_POST';
export const ERROR_VOTE_POST = 'ERROR_VOTE_POST';

export const ERROR_POSTS = 'ERROR_POSTS';
export const GET_POSTS = 'GET_POSTS';
export const SORT_POSTS_FIELD = 'SORT_POSTS_FIELD';
export const SORT_POSTS_DIRECTION = 'SORT_POSTS_DIRECTION';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const ERROR_CREATE_COMMENT = 'ERROR_CREATE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const ERROR_EDIT_COMMENT = 'ERROR_EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ERROR_DELETE_COMMENT = 'ERROR_DELETE_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const ERROR_VOTE_COMMENT = 'ERROR_VOTE_COMMENT';

export const GET_COMMENTS = 'GET_COMMENTS';
export const ERROR_COMMENTS = 'ERROR_COMMENTS';

export const SET_MODE = 'SET_MODE';
